const CAPSTONE_HISTORY = 
[
    {
      "ApplicationType": "Web Form",
      "FrontendLanguage": "HTML5",
      "BackendLanguage": "PHP",
      "RowsFunctionality": 21,
      "FunctionsOnChart": 50,
      "LOC": 5046,
      "TimeHours": 168,
      "ClassAmount": 10,
      "TableAmount": 7,
      "AverageFieldsPerTable": 6,
      "PageAmount": 9,
      "SecurityLevel": "Secure",
      "TestPlan": "Yes"
    },
    {
      "ApplicationType": "Website",
      "FrontendLanguage": "HTML5",
      "BackendLanguage": "None",
      "RowsFunctionality": 48,
      "FunctionsOnChart": 56,
      "LOC": 3660,
      "TimeHours": 414,
      "ClassAmount": 0,
      "TableAmount": 0,
      "AverageFieldsPerTable": 0,
      "PageAmount": 15,
      "SecurityLevel": "No Security",
      "TestPlan": "No"
    },
    {
      "ApplicationType": "Web Form",
      "FrontendLanguage": "HTML5",
      "BackendLanguage": "PHP",
      "RowsFunctionality": 21,
      "FunctionsOnChart": 32,
      "LOC": 4600,
      "TimeHours": 136,
      "ClassAmount": 7,
      "TableAmount": 3,
      "AverageFieldsPerTable": 6,
      "PageAmount": 5,
      "SecurityLevel": "Secure",
      "TestPlan": "Yes"
    },
    {
      "ApplicationType": "Console Application",
      "FrontendLanguage": "C#",
      "BackendLanguage": "None",
      "RowsFunctionality": 35,
      "FunctionsOnChart": 42,
      "LOC": 2560,
      "TimeHours": 120,
      "ClassAmount": 5,
      "TableAmount": 4,
      "AverageFieldsPerTable": 5,
      "PageAmount": 3,
      "SecurityLevel": "No Security",
      "TestPlan": "Yes"
    },
    {
      "ApplicationType": "Mobile App",
      "FrontendLanguage": "Java",
      "BackendLanguage": "Java",
      "RowsFunctionality": 25,
      "FunctionsOnChart": 35,
      "LOC": 2045,
      "TimeHours": 115,
      "ClassAmount": 7,
      "TableAmount": 5,
      "AverageFieldsPerTable": 6,
      "PageAmount": 8,
      "SecurityLevel": "Secure",
      "TestPlan": "Yes"
    },
    {
      "ApplicationType": "Game",
      "FrontendLanguage": "C#",
      "BackendLanguage": "C#",
      "RowsFunctionality": 45,
      "FunctionsOnChart": 73,
      "LOC": 4278,
      "TimeHours": 386,
      "ClassAmount": 13,
      "TableAmount": 10,
      "AverageFieldsPerTable": 7,
      "PageAmount": 10,
      "SecurityLevel": "Secure",
      "TestPlan": "Yes"
    },
    {
      "ApplicationType": "Windows Forms",
      "FrontendLanguage": "VB.NET",
      "BackendLanguage": "VB.NET",
      "RowsFunctionality": 38,
      "FunctionsOnChart": 38,
      "LOC": 1282,
      "TimeHours": 200,
      "ClassAmount": 8,
      "TableAmount": 3,
      "AverageFieldsPerTable": 5,
      "PageAmount": 6,
      "SecurityLevel": "No Security",
      "TestPlan": "Yes"
    }
  ];